<a href="https://colab.research.google.com/github/maurishi09/maurishi09/blob/main/assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import ttest_ind
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    confusion_matrix,
    classification_report
)

In [ ]:
df = pd.read_csv("/content/Assignment 3.csv")

In [ ]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [ ]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip().str.lower()

In [ ]:
df['y_encoded'] = df['y'].map({'no': 0, 'yes': 1})

In [ ]:
df['age'].describe()

count    45211.000000
mean        40.936210
std         10.618762
min         18.000000
25%         33.000000
50%         39.000000
75%         48.000000
max         95.000000
Name: age, dtype: float64

In [ ]:
df.groupby('job')['age'].mean().sort_values(ascending=False)

job
retired          61.626767
unknown          47.593750
housemaid        46.415323
entrepreneur     42.190989
unemployed       40.961627
self-employed    40.484484
management       40.449567
blue-collar      40.044081
technician       39.314598
admin.           39.289886
services         38.740250
student          26.542644
Name: age, dtype: float64

In [ ]:
df['marital'].value_counts()

marital
married     27214
single      12790
divorced     5207
Name: count, dtype: int64

In [ ]:
df['education'].value_counts()

education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

In [ ]:
pd.crosstab(df['housing'], df['loan'])

loan        no   yes
housing
no       17204  2877
yes      20763  4367

In [ ]:
df['campaign'].describe()

count    45211.000000
mean         2.763841
std          3.098021
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max         63.000000
Name: campaign, dtype: float64

In [ ]:
df.groupby('campaign')['y_encoded'].mean()

campaign
1     0.145976
2     0.112035
3     0.111936
4     0.090006
5     0.078798
6     0.071263
7     0.063946
8     0.059259
9     0.064220
10    0.052632
11    0.079602
12    0.025806
13    0.045113
14    0.043011
15    0.047619
16    0.025316
17    0.086957
18    0.000000
19    0.000000
20    0.023256
21    0.028571
22    0.000000
23    0.000000
24    0.050000
25    0.000000
26    0.000000
27    0.000000
28    0.000000
29    0.062500
30    0.000000
31    0.000000
32    0.111111
33    0.000000
34    0.000000
35    0.000000
36    0.000000
37    0.000000
38    0.000000
39    0.000000
41    0.000000
43    0.000000
44    0.000000
46    0.000000
50    0.000000
51    0.000000
55    0.000000
58    0.000000
63    0.000000
Name: y_encoded, dtype: float64

In [ ]:
from scipy.stats import ttest_ind

housing_yes = df[df['housing']=='yes']['balance']
housing_no = df[df['housing']=='no']['balance']

t_stat, p_value = ttest_ind(
    housing_yes,
    housing_no,
    equal_var=False
)

print(t_stat)
print(p_value)

-14.081117553694206
6.625425926072512e-45

In [ ]:
df['duration'].corr(df['y_encoded'])
df['campaign'].corr(df['y_encoded'])
df['previous'].corr(df['y_encoded'])

np.float64(0.09323577278887688)

In [ ]:
RandomForestClassifier

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [ ]:
categorical_features = X.select_dtypes(include=['object']).columns
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features),
        ('num', 'passthrough', numerical_features)
    ])

model = Pipeline(steps=[('preprocessor', preprocessor),
                        ('classifier', RandomForestClassifier(random_state=42))])

model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'poutcome'],
      dtype='object')),
                                                 ('num', 'passthrough',
                                                  Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous'], dtype='object'))])),
                ('classifier', RandomForestClassifier(random_state=42))])